### ISSUE TITLE
How about letting `watch` or some other tool handle the redrawing

### ISSUE THREAD

**Issue by berkes** [bugaiov/capwatch#4]
I think this tool would be more valuable if it outputs once and than exits. 

That would allow:

* `watch -c` for making a refreshable, watchable output.
* `crontab` for mailing hourly/daily reports.
* `sed/awk/grep` to extract or reformat in order to create simple reports.
* nice integration tests with e.g. `aruba`.

My *personal* preference would be to have no watch option in here at all: to have all the looping-and-clearing removed.
Second best *for me*, would be a `-w` or `-t` (tail) option that enables watching/redrawing.
Third best, *for me*, would be a `-no-w` or `-no-t` option, that disables the watching and tailing.

It probably goes against the name and maybe purpose of this gem, but IMO the [Unix Philosophy sums it up](https://en.wikipedia.org/wiki/Unix_philosophy) pretty well:

>     Write programs that do one thing and do it well.
>     Write programs to work together.
>     Write programs to handle text streams, because that is a universal interface.

What do you think? Would a PR where I remove the looping and replace it with a single-run-then-output be welcome?

**Comment by bugaiov** [comment]
Hi @berkes 

Thanks for the interest in the project.

I think you're right. I'd vote for the second option with a `-t` param. Since I'm using and a lot. Also I understand that it could be done via external program like `watch -n2 capwatch` but I want to have it included since I don't want to care about other programs.

Everything else (I'm personally) don't need. If you want to develop different formating/reports etc. I'll be fine to include those options in the program but I myself probably would not use them.

>What do you think? Would a PR where I remove the looping and replace it with a single-run-then-output be welcome?

Yes, if I still have the `-t` option.

N

**Comment by bugaiov** [comment]
@berkes btw, I've implemented parts of the ticket.
If you don't mind, I'll close the ticket unless you want to discuss further

**Comment by berkes** [comment]
I already saw it. But forgot to close the PR. So go ahead. And thanks!

Nick Bugaiov <notifications@github.com> schreef op 5 februari 2018 20:41:37 GMT+07:00:
>@berkes btw, I've implemented parts of the ticket.
>If you don't mind, I'll close the ticket unless you want to discuss
>further 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/bugaiov/capwatch/issues/4#issuecomment-363087545

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by bugaiov** [comment]
🆗
